#!/bin/csh -f
 
                        set WORKDIR = /home/${user}/tmpdir
if ( ! -e $WORKDIR ) mkdir $WORKDIR
                        cd $WORKDIR

alias rm  "rm -f"
 
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#         TABULATE TROPICAL STORM STATISTICS          
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#===============================================================
# --- input
#===============================================================

if ( ( $1 == "-help" ) || ( $1 == "-h" ) ) then
#--------------------------------------------------
   echo "   "
   echo "   Input Aguments:"
   echo "   1) path name of directory where tropical storm data are stored "
   echo "   2) starting year                                               "
   echo "   3) ending year                                                 "
   echo "   4) also do obs (y/n)                                           "
   echo "   "
   exit
#--------------------------------------------------
else
#--------------------------------------------------
   set indir    = $1 ; shift
   set year_beg = $1 ; shift                                           
   set year_end = $1 ; shift        
   set do_obs   = $1 ; shift                           
   set opt      = $1                         
#--------------------------------------------------
endif

#===============================================================
# --- pathnames & directories
#===============================================================

# --- executable
set ori_stat = /home/fms/local/opt/fre-analysis/test/keo/tropical_storms/miztstorm/src_misc/stat_ori_mask.exe
cp $ori_stat ori_stat.exe

# --- input 
set fori = ${indir}/ori             
 
# --- output 
set fstats = ${indir}/stats 
              
#===============================================================
# --- namelist
#===============================================================

cat << eof > nml_inp
 &input  &end
eof

#===============================================================
# --- get data & run
#===============================================================

       @ year  = $year_beg
while ( $year <= $year_end )
    cat ${fori}_${year} >> ori
@ year ++
end

ori_stat.exe < nml_inp
mv stat_mo ${fstats}_model_${year_beg}-${year_end} 
rm ori

if ( $do_obs == n ) goto tixe

if ($opt == hur) then
    set fobs = /home/fms/local/opt/fre-analysis/test/keo/tropical_storms/ibtracs/obs_hur/ori
else
    set fobs = /home/fms/local/opt/fre-analysis/test/keo/tropical_storms/ibtracs/ori
endif

       @ year  = $year_beg
while ( $year <= $year_end )
    cat ${fobs}_${year} >> ori
@ year ++
end

ori_stat.exe < nml_inp
mv stat_mo ${fstats}_obs_${year_beg}-${year_end} 

#================================================
tixe:
  rm nml_inp
  rm ori
  rm ori_stat.exe
exit
